apiVersion: v1
kind: Service
metadata:
  name: {{ include "secure-auth-platform.fullname" . }}-auth-api
  labels:
    {{- include "secure-auth-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth-api
spec:
  type: {{ .Values.authApi.service.type }}
  ports:
    - port: {{ .Values.authApi.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "secure-auth-platform.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: auth-api
