apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "secure-auth-platform.fullname" . }}-auth-api-pdb
  labels:
    {{- include "secure-auth-platform.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "secure-auth-platform.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: auth-api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "secure-auth-platform.fullname" . }}-web-pdb
  labels:
    {{- include "secure-auth-platform.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "secure-auth-platform.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: web
