apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-secret
  namespace: data
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: auth-rust-svelte
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore

  target:
    name: postgres-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      engineVersion: v2

  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: postgres
        property: POSTGRES_USER

    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: postgres
        property: POSTGRES_PASSWORD

    - secretKey: POSTGRES_DB
      remoteRef:
        key: postgres
        property: POSTGRES_DB
