apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - namespace.yaml
  - otel-collector/daemonset.yaml
  - otel-collector/service.yaml
  - otel-collector/configmap.yaml
  - prometheus/service-monitor.yaml
  - prometheus/rules.yaml
  - grafana/configmap-dashboards.yaml
---
# Observability namespace
apiVersion: v1
kind: Namespace
metadata:
  name: observability
